events {}

http {
    upstream books {
        server book-service:8000;
    }
    upstream users {
        server user-service:8000;
    }
    upstream loans {
        server loan-service:8000;
    }
    upstream reviews {
        server review-service:8000;
    }
    upstream inventory {
        server inventory-service:8000;
    }
    upstream notifications {
        server notification-service:8000;
    }

    server {
        listen 80;

        location /health {
            proxy_pass http://books;
        }

        location /books {
            proxy_pass http://books;
        }

        location /users {
            proxy_pass http://users;
        }

        location /loans {
            proxy_pass http://loans;
        }

        location /reviews {
            proxy_pass http://reviews;
        }

        location /inventory {
            proxy_pass http://inventory;
        }

        location /notifications {
            proxy_pass http://notifications;
        }
    }
}
